### ISSUE TITLE
Add associate developer methods

### ISSUE THREAD

**Issue by theophoric** [IBM-Bluemix/cf-nodejs-client#14]

**Comment by jsloyer** [comment]
@theophoric what do you mean associate methods?

**Comment by theophoric** [comment]
e.g. http://apidocs.cloudfoundry.org/214/spaces/associate_developer_with_the_space.html

**Comment by theophoric** [comment]
methods added in https://github.com/IBM-Bluemix/cf-nodejs-client/commit/4ffadd653ad15c8a23d76fb0d207a51904ec7024
