### ISSUE TITLE
Doc links are broken.

### ISSUE THREAD

**Issue by kurtismgit** [IBM-Bluemix/cf-nodejs-client#17]
https://ibm-bluemix.github.io
Seems to be down, so several links mentioned in the readme, including the JSDoc for this library, are inaccessible.

**Comment by jsloyer** [comment]
related to #12

**Comment by jsloyer** [comment]
resolved in https://github.com/IBM-Bluemix/cf-nodejs-client/commit/51b4181d440db2b831243fe164986717acea6611#diff-04c6e90faac2675aa89e2176d2eec7d8
