### ISSUE TITLE
ws@1.1.0 is causing david-dm to flag dependencies as insecure

### ISSUE THREAD

**Issue by aeweidne** [IBM-Bluemix/cf-nodejs-client#31]
looks like it is fixed in 1.1.1: https://nodesecurity.io/advisories/socketio_dos-due-to-excessively-large-websocket-message

gonna open a PR to make the change.

**Comment by jsloyer** [comment]
resolved in [`0.13.24`](https://github.com/IBM-Bluemix/cf-nodejs-client/releases/tag/v0.13.24)
